# Generated by Django 4.2.3 on 2023-07-27 17:06

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=245)),
                ('numero', models.IntegerField()),
                ('psedo', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=245)),
                ('libelle2', models.CharField(max_length=245)),
                ('numero', models.IntegerField()),
                ('etat', models.CharField(max_length=245)),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='comptes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=245)),
                ('numero', models.CharField(max_length=50)),
                ('statut', models.CharField(max_length=50, null=True)),
                ('psedo', models.IntegerField(default=0)),
                ('categorie', models.ForeignKey(db_column='categorie_id', on_delete=django.db.models.deletion.CASCADE, to='app.categories')),
            ],
            options={
                'db_table': 'comptes',
            },
        ),
        migrations.CreateModel(
            name='ecritures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dte', models.DateField()),
                ('dteaff', models.DateField(default=None, null=True)),
                ('dtetime', models.DateTimeField()),
                ('libelle', models.CharField(max_length=245)),
                ('reference', models.CharField(default=None, max_length=50, null=True)),
                ('beneficiaire', models.CharField(default=None, max_length=100, null=True)),
                ('psedo', models.IntegerField(default=0)),
                ('devise', models.CharField(default=None, max_length=10, null=True)),
                ('lettrer', models.IntegerField(default=0)),
                ('dteupdt', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'ecritures',
            },
        ),
        migrations.CreateModel(
            name='entreprises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('idnat', models.CharField(max_length=100)),
                ('rccm', models.CharField(max_length=100)),
                ('taux', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='exercices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lib', models.CharField(default=None, max_length=50, null=True)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('annee', models.IntegerField(default=None, null=True)),
                ('etat', models.IntegerField(default=0)),
                ('psedo', models.IntegerField(default=0)),
                ('preseance', models.IntegerField(default=3)),
                ('resultat', models.IntegerField(default=0)),
                ('existe', models.IntegerField(default=0)),
                ('ecriture', models.IntegerField(default=0)),
                ('cloture', models.IntegerField(default=0)),
                ('entreprise', models.ForeignKey(db_column='entreprise_id', on_delete=django.db.models.deletion.CASCADE, to='app.entreprises')),
            ],
            options={
                'db_table': 'exercices',
            },
        ),
        migrations.CreateModel(
            name='journaux',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('libelle', models.CharField(max_length=245)),
                ('psedo', models.IntegerField(default=0)),
                ('entreprise', models.ForeignKey(db_column='entreprise_id', on_delete=django.db.models.deletion.CASCADE, to='app.entreprises')),
            ],
            options={
                'db_table': 'journaux',
            },
        ),
        migrations.CreateModel(
            name='modelesRapportsCompta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('compte_id', models.CharField(default='0', max_length=200)),
                ('saufbrut', models.CharField(default='0', max_length=200)),
                ('partielbrut', models.CharField(default=None, max_length=200, null=True)),
                ('rubrique', models.CharField(default=None, max_length=200, null=True)),
                ('solde', models.IntegerField(default=0, help_text='0 peu importe 1 debiteur 2 crediteur')),
                ('signevar', models.CharField(default=None, max_length=10, null=True)),
                ('code', models.CharField(max_length=10)),
                ('amortprov', models.CharField(default='0', max_length=200)),
                ('saufamort', models.CharField(default=None, max_length=200, null=True)),
                ('partielamort', models.CharField(default=None, max_length=200, null=True)),
                ('format', models.IntegerField(default=3)),
                ('ref', models.CharField(default=None, max_length=10, null=True)),
                ('note', models.CharField(default=None, max_length=10, null=True)),
                ('signe', models.IntegerField(default=None, help_text='-1=-;1=+;0=-/+', null=True)),
                ('typeligne', models.IntegerField(default=0, help_text='-1=souscompte;0=compte;1=categorie;2=total')),
                ('ba', models.IntegerField(default=0)),
                ('bp', models.IntegerField(default=0)),
                ('r', models.IntegerField(default=0, help_text='0=pas un compte resultat, 1=charge ,2 =produit')),
            ],
            options={
                'db_table': 'modelesRapportsCompta',
            },
        ),
        migrations.CreateModel(
            name='souscomptes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=245)),
                ('numero', models.CharField(max_length=50)),
                ('psedo', models.IntegerField(default=0)),
                ('modif', models.IntegerField(default=0)),
                ('suffixe', models.CharField(default=None, max_length=100, null=True)),
                ('compte', models.ForeignKey(db_column='compte_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comptes')),
                ('entreprise', models.ForeignKey(db_column='entreprise_id', on_delete=django.db.models.deletion.CASCADE, to='app.entreprises')),
            ],
            options={
                'db_table': 'souscomptes',
            },
        ),
        migrations.CreateModel(
            name='rapportjournal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dte', models.DateField(default=None, null=True)),
                ('ref', models.CharField(default=None, max_length=50, null=True)),
                ('compte', models.CharField(default=None, max_length=200, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('debit', models.DecimalField(decimal_places=10, default=0, max_digits=65)),
                ('credit', models.DecimalField(decimal_places=10, default=0, max_digits=65)),
                ('devise', models.CharField(default=None, max_length=20, null=True)),
                ('psedo', models.IntegerField(default=0)),
                ('benprov', models.CharField(default=None, max_length=254, null=True)),
                ('ecriture', models.ForeignKey(db_column='ecriture_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ecritures')),
                ('entreprise', models.ForeignKey(db_column='entreprise_id', on_delete=django.db.models.deletion.CASCADE, to='app.entreprises')),
                ('exercice', models.ForeignKey(db_column='exercice_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.exercices')),
                ('journal', models.ForeignKey(db_column='journal_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.journaux')),
            ],
            options={
                'db_table': 'rapportjournal',
            },
        ),
        migrations.AddField(
            model_name='ecritures',
            name='entreprise',
            field=models.ForeignKey(db_column='entreprise_id', on_delete=django.db.models.deletion.CASCADE, to='app.entreprises'),
        ),
        migrations.AddField(
            model_name='ecritures',
            name='exercice',
            field=models.ForeignKey(db_column='exercice_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.exercices'),
        ),
        migrations.AddField(
            model_name='ecritures',
            name='journal',
            field=models.ForeignKey(db_column='journal_id', on_delete=django.db.models.deletion.CASCADE, to='app.journaux'),
        ),
        migrations.AddField(
            model_name='ecritures',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='detailsecritures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('debit', models.DecimalField(decimal_places=10, default=0, max_digits=65)),
                ('credit', models.DecimalField(decimal_places=10, default=0, max_digits=65)),
                ('libelle', models.CharField(default=None, max_length=245, null=True)),
                ('numdoc', models.CharField(default=None, max_length=245, null=True)),
                ('devise', models.CharField(default=None, max_length=10, null=True)),
                ('taux', models.IntegerField(default=None, null=True)),
                ('compte_ecriture', models.CharField(default=None, max_length=200, null=True)),
                ('long_compte', models.IntegerField(default=0)),
                ('categorie', models.ForeignKey(db_column='categorie_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.categories')),
                ('compte', models.ForeignKey(db_column='compte_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comptes')),
                ('ecriture', models.ForeignKey(db_column='ecriture_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ecritures')),
                ('entreprise', models.ForeignKey(db_column='entreprise_id', on_delete=django.db.models.deletion.CASCADE, to='app.entreprises')),
                ('souscompte', models.ForeignKey(db_column='souscompte_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.souscomptes')),
            ],
            options={
                'db_table': 'detailsecritures',
            },
        ),
        migrations.CreateModel(
            name='compteur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=245)),
                ('numero', models.IntegerField()),
                ('entreprise', models.ForeignKey(db_column='entreprise_id', on_delete=django.db.models.deletion.CASCADE, to='app.entreprises')),
            ],
            options={
                'db_table': 'compteur',
            },
        ),
        migrations.CreateModel(
            name='compteEntreprise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('compte', models.ForeignKey(db_column='compte_id', on_delete=django.db.models.deletion.CASCADE, to='app.comptes')),
                ('entreprise', models.ForeignKey(db_column='entreprise_id', on_delete=django.db.models.deletion.CASCADE, to='app.entreprises')),
            ],
            options={
                'db_table': 'compteEntreprise',
            },
        ),
        migrations.AddField(
            model_name='categories',
            name='classe',
            field=models.ForeignKey(db_column='classe_id', on_delete=django.db.models.deletion.CASCADE, to='app.classes'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.entreprises'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='journalcompte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('compte_num', models.IntegerField(default=None, null=True)),
                ('long_compte', models.IntegerField(default=None, null=True)),
                ('journal', models.ForeignKey(db_column='journal_id', on_delete=django.db.models.deletion.CASCADE, to='app.journaux')),
            ],
            options={
                'db_table': 'journalcompte',
                'unique_together': {('compte_num', 'journal')},
            },
        ),
    ]
