# Generated by Django 4.2.3 on 2023-07-28 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souscomptes',
            name='entreprise',
            field=models.ForeignKey(db_column='entreprise_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.entreprises'),
        ),
    ]
