# Generated by Django 4.2.3 on 2023-07-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_journaux_entreprise'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='journalcompte',
            unique_together=set(),
        ),
    ]
