# Generated by Django 4.2.3 on 2023-07-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_journalcompte_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelesrapportscompta',
            name='compte_id',
            field=models.CharField(default='0', max_length=200, null=True),
        ),
    ]
