# Generated by Django 4.2.3 on 2023-08-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_compteentreprise'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entreprises',
            table='entreprises',
        ),
    ]
