# Generated by Django 4.2.3 on 2023-08-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='jwt_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
