# Generated by Django 4.2.3 on 2023-08-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_customuser_jwt_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='jwt_token',
        ),
    ]
