# Generated by Django 4.2.3 on 2023-09-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souscomptes',
            name='modif',
            field=models.IntegerField(default=1),
        ),
    ]
