# Generated by Django 4.2.3 on 2023-09-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_souscomptes_modif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souscomptes',
            name='id',
            field=models.AutoField(default=3000, primary_key=True, serialize=False),
        ),
    ]
