# Generated by Django 4.2.3 on 2023-09-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_souscomptes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souscomptes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
