# Generated by Django 4.2.3 on 2023-09-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_souscomptes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprises',
            name='site_web',
            field=models.TextField(blank=True, null=True),
        ),
    ]
