# Generated by Django 4.2.3 on 2023-09-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_entreprises_site_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprises',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
