# Generated by Django 4.2.3 on 2023-09-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_entreprises_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprises',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
